#!/usr/bin/env python

# This script executes all arguments as shell scripts in the same folder.
# example usage: 
# 
# create new shell script named after your project
# insert all commands you want to be executed when "work <your project name>" is called
# make it executable with "chmod +x <shellfile>"
# enjoy at least a few seconds saved in time


import sys
import os 
import os.path
import subprocess

dir_path = os.path.dirname(os.path.realpath(__file__))

for arg in sys.argv:
    if arg == __file__:
        continue
    if os.path.isfile(os.path.join(dir_path, arg + ".sh")):
        os.system(os.path.join(dir_path, arg + ".sh"))
    else:
        print("Script '" + arg + "' not found!")